export const data = {
  groups: [
    {
      type: 'all',
      newests: [
        {
          id: 0,
          name: 'جدیدترین 1 ',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 1,

          name: 'جدیدترین 2 ',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 2,

          name: 'جدیدترین3 ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 3,

          name: 'جدیدترین 4',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
      ],
      bestSellers: [
        {
          id: 0,
          name: 'پرفروش  1 ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 1,

          name: 'پرفروش  2 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 2,

          name: 'پرفروش 3 ',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 3,

          name: 'پرفروش 4',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
      ],
      all: [
        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'لباس',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'موبایل',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '2/500/000',
          prevPrice: '3/500/000',
          discount: '500000',
        },
        {
          id: 0,
          name: 'کیف',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'موبایل',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },

        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '2/500/000',
          prevPrice: '3/500/000',
          discount: '500000',
        },
      ],
    },
    {
      type: 'bags',
      newests: [
        {
          id: 0,
          name: 'جدیدترین 1 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 1,

          name: 'جدیدترین 2 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 2,

          name: 'جدیدترین3 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 3,

          name: 'جدیدترین 4',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
      ],
      bestSellers: [
        {
          id: 0,
          name: 'پرفروش  1 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 1,

          name: 'پرفروش  2 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 2,

          name: 'پرفروش 3 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 3,

          name: 'پرفروش 4',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
      ],
      all: [
        {
          id: 0,
          name: '  کیف 1 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: '  کیف 2 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: '  کیف 3 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: '  کیف 4 ',
          cover: '/assets/images/bag.jpg',
          price: '2/500/000',
          prevPrice: '3/500/000',
          discount: '500000',
        },
        {
          id: 0,
          name: '  کیف 5 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: '  کیف 6 ',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'کیف 7',
          cover: '/assets/images/bag.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: '  کیف 8 ',
          cover: '/assets/images/bag.jpg',
          price: '2/500/000',
          prevPrice: '3/500/000',
          discount: '500000',
        },
      ],
    },
    {
      type: 'car',
      newests: [
        {
          id: 0,
          name: 'جدیدترین 1 ',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 1,

          name: 'جدیدترین 2 ',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 2,

          name: 'جدیدترین3 ',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 3,

          name: 'جدیدترین 4',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
      ],
      bestSellers: [
        {
          id: 0,
          name: 'پرفروش  1 ',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 1,

          name: 'پرفروش  2 ',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 2,

          name: 'پرفروش 3 ',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 3,

          name: 'پرفروش 4',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
      ],
      all: [
        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '2/500/000',
          prevPrice: '3/500/000',
          discount: '500000',
        },
        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'کیت کلاچ میتسوبیشی لنسر',
          cover: '/assets/images/product.png',
          price: '2/500/000',
          prevPrice: '3/500/000',
          discount: '500000',
        },
      ],
    },
    {
      type: 'digital',
      newests: [
        {
          id: 0,
          name: 'جدیدترین 1 ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 1,

          name: 'جدیدترین 2 ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 2,

          name: 'جدیدترین3 ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 3,

          name: 'جدیدترین 4',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
      ],
      bestSellers: [
        {
          id: 0,
          name: 'پرفروش  1 ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 1,

          name: 'پرفروش  2 ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 2,

          name: 'پرفروش 3 ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 3,

          name: 'پرفروش 4',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
      ],
      all: [
        {
          id: 0,
          name: 'موبایل1  ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'موبایل2  ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'موبایل3  ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'موبایل4 ',
          cover: '/assets/images/iphone.png',
          price: '2/500/000',
          prevPrice: '3/500/000',
          discount: '500000',
        },
        {
          id: 0,
          name: 'موبایل5   ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'موبایل6  ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'موبایل7  ',
          cover: '/assets/images/iphone.png',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'موبایل8  ',
          cover: '/assets/images/iphone.png',
          price: '2/500/000',
          prevPrice: '3/500/000',
          discount: '500000',
        },
      ],
    },
    {
      type: 'clothes',
      newests: [
        {
          id: 0,
          name: 'جدیدترین 1 ',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 1,

          name: 'جدیدترین 2 ',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 2,

          name: 'جدیدترین3 ',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 3,

          name: 'جدیدترین 4',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
      ],
      bestSellers: [
        {
          id: 0,
          name: 'پرفروش  1 ',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 1,

          name: 'پرفروش  2 ',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 2,

          name: 'پرفروش 3 ',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 3,

          name: 'پرفروش 4',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
      ],
      all: [
        {
          id: 0,
          name: 'پوشاک 1',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'پوشاک 2',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'پوشاک 3',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'پوشاک 4',
          cover: '/assets/images/clothes.jpg',
          price: '2/500/000',
          prevPrice: '3/500/000',
          discount: '500000',
        },
        {
          id: 0,
          name: 'پوشاک 5',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'پوشاک 6',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'پوشاک 7',
          cover: '/assets/images/clothes.jpg',
          price: '3/000/000',
          prevPrice: null,
          discount: '500000',
        },
        {
          id: 0,
          name: 'پوشاک  8',
          cover: '/assets/images/clothes.jpg',
          price: '2/500/000',
          prevPrice: '3/500/000',
          discount: '500000',
        },
      ],
    },
  ],
};
