export const designInitialState = {
  menuItems: [
    {
      id: '0',
      type: 'slider',
      title: 'اسلایدر',
      images: [],
    },
    {
      id: '1',
      type: 'products',
      title: 'لیست محصولات',
      displayMode: 'list',
      showBy: 'newest',
      pagination: false,
      images: [],
      settings: {},
      groups: [
        {
          type: 'specialOffer',
          groupName: 'پیشنهاد ویژه',
          groupItems: [
            {
              id: 0,
              name: 'کیت کلاچ میتسوبیشی لنسر',
              cover: '/assets/images/product.png',
              price: '3/000/000',
              prevPrice: null,
              discount: '500000',
            },
            {
              id: 0,
              name: 'کیت کلاچ میتسوبیشی لنسر',
              cover: '/assets/images/product.png',
              price: '3/000/000',
              prevPrice: null,
              discount: '500000',
            },
            {
              id: 0,
              name: 'کیت کلاچ میتسوبیشی لنسر',
              cover: '/assets/images/product.png',
              price: '3/000/000',
              prevPrice: null,
              discount: '500000',
            },
            {
              id: 0,
              name: 'کیت کلاچ میتسوبیشی لنسر',
              cover: '/assets/images/product.png',
              price: '2/500/000',
              prevPrice: '3/500/000',
              discount: '500000',
            },
            {
              id: 0,
              name: 'کیت کلاچ میتسوبیشی لنسر',
              cover: '/assets/images/product.png',
              price: '3/000/000',
              prevPrice: null,
              discount: '500000',
            },
            {
              id: 0,
              name: 'کیت کلاچ میتسوبیشی لنسر',
              cover: '/assets/images/product.png',
              price: '3/000/000',
              prevPrice: null,
              discount: '500000',
            },
            {
              id: 0,
              name: 'کیت کلاچ میتسوبیشی لنسر',
              cover: '/assets/images/product.png',
              price: '3/000/000',
              prevPrice: null,
              discount: '500000',
            },
            {
              id: 0,
              name: 'کیت کلاچ میتسوبیشی لنسر',
              cover: '/assets/images/product.png',
              price: '2/500/000',
              prevPrice: '3/500/000',
              discount: '500000',
            },
          ],
        },

        {
          id: '2',
          type: 'banner',
          title: 'بنر',
          images: [],
        },
        {
          id: '3',
          type: 'brands',
          title: 'برندها',
          images: [],
        },
        {
          id: '4',
          type: 'slider',
          title: 'لیست اخبار',
        },
        {
          id: '5',
          type: 'slider',
          title: 'متن با تصویر',
        },
        {
          id: '6',
          type: 'slider',
          title: 'نظرات مشتریان',
        },
        {
          id: '7',
          type: 'text',
          title: 'متن',
        },
        {
          id: '8',
          type: 'slider',
          title: 'لیست محصولات',
        },
      ],
    },
    {
      id: '2',
      type: 'banner',
      title: 'بنر',
      images: [],
    },
    {
      id: '3',
      type: 'brands',
      title: 'برندها',
      images: [],
    },
    {
      id: '4',
      type: 'slider',
      title: 'لیست اخبار',
    },
    {
      id: '5',
      type: 'slider',
      title: 'متن با تصویر',
    },
    {
      id: '6',
      type: 'slider',
      title: 'نظرات مشتریان',
    },
    {
      id: '7',
      type: 'text',
      title: 'متن',
    },
    {
      id: '8',
      type: 'slider',
      title: 'لیست محصولات',
    },
  ],
  pageItems: [
    {
      uuid: 'HEADER',
      type: 'header',
      title: 'هدر',
      images: [],
    },
    {
      uuid: 'FOOTER',
      type: 'footer',
      title: 'فوتر',
    },
  ],
  pageSettings: {
    key: 'main',
    titleFont: 'yekan',
    textFont: 'yekan',
    primary: '',
    secondary: '',
  },
  current: {
    uuid: '',
    settings: {
      imageSetting: false,
    },
    images: [{ number: 'one', value: 'sfdsf', newTab: false, link: '' }],
  },
  pureImage: {
    number: '',
    value: '',
    newTab: false,
    link: '',
    onUpload: false,
    title: '',
    description: '',
  },
};
