export * from './edit-alt';
export * from './plus';
export * from './setting';
export * from './menu';
export * from './multiply';
export * from './setting-cog';
export * from './trash';
export * from './logo';
export * from './link';
export * from './arrow-right';
export * from './edit-setting';
export * from './angle-up';
export * from './angle-down';
export * from './link-h'